# Generated by Django 5.2.4 on 2025-07-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('period', models.DateField()),
                ('teacher_count', models.IntegerField()),
                ('avg_lp_ratio', models.FloatField()),
                ('period_type', models.CharField(default='weekly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['school'], name='api_aggrega_school_0bc83f_idx'), models.Index(fields=['sector'], name='api_aggrega_sector_b1c2da_idx'), models.Index(fields=['period'], name='api_aggrega_period_11be9b_idx'), models.Index(fields=['period_type'], name='api_aggrega_period__87b903_idx')],
            },
        ),
        migrations.CreateModel(
            name='FilterOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(max_length=20)),
                ('option_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['option_type'], name='api_filtero_option__f56dce_idx')],
                'unique_together': {('option_type', 'option_value')},
            },
        ),
        migrations.CreateModel(
            name='SchoolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('emis', models.CharField(max_length=50)),
                ('teacher_count', models.IntegerField()),
                ('avg_lp_ratio', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['school_name'], name='api_schoold_school__c820c3_idx'), models.Index(fields=['sector'], name='api_schoold_sector_834ed1_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('teacher', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('emis', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=255)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('week_number', models.IntegerField()),
                ('lp_ratio', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['school'], name='api_teacher_school_477d77_idx'), models.Index(fields=['sector'], name='api_teacher_sector_8813f4_idx'), models.Index(fields=['grade'], name='api_teacher_grade_edc023_idx'), models.Index(fields=['subject'], name='api_teacher_subject_b6780d_idx'), models.Index(fields=['week_start'], name='api_teacher_week_st_064384_idx')],
            },
        ),
    ]
