# Generated by Django 5.2.4 on 2025-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datasynclog_aggregateddata_filteroptions_schooldata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('teacher', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('emis', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='api_usersch_user_id_4fff46_idx'), models.Index(fields=['school'], name='api_usersch_school_b7d912_idx'), models.Index(fields=['sector'], name='api_usersch_sector_f26ade_idx')],
            },
        ),
    ]
