# Generated by Django 5.2.4 on 2025-07-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userschoolprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
