# Generated by Django 5.2.4 on 2025-07-31 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_conversation_fde_alter_conversation_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='fde',
        ),
    ]
