# Generated by Django 5.2.4 on 2025-08-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_conversation_fde'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100, unique=True)),
                ('teacher_count', models.IntegerField()),
                ('avg_lp_ratio', models.FloatField()),
                ('school_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sector'], name='api_sectord_sector_12f8f6_idx')],
            },
        ),
    ]
