# Generated by Django 5.2.4 on 2025-08-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sectordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldata',
            name='internet_availability',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='schooldata',
            name='student_teacher_ratio',
            field=models.CharField(default='1:0', max_length=20),
        ),
    ]
