# Generated by Django 5.2.4 on 2025-08-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_schooldata_internet_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
