# Generated by Django 5.2.4 on 2025-08-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='api_userlog_user_id_5de1ae_idx'), models.Index(fields=['username'], name='api_userlog_usernam_fdab55_idx'), models.Index(fields=['date'], name='api_userlog_date_0e85f7_idx'), models.Index(fields=['created_at'], name='api_userlog_created_07a934_idx')],
            },
        ),
    ]
