#!/bin/bash

echo "🔧 Comprehensive CORS Fix"
echo "========================"
echo ""

echo "📋 Current Status Analysis:"
echo "=========================="
echo "✅ Server is responding (nginx)"
echo "❌ Django settings not being used"
echo "❌ CORS headers missing"
echo "❌ ALLOWED_HOSTS not updated"
echo ""

echo "🚨 Root Cause:"
echo "=============="
echo "The requests are being handled by Nginx, not Django."
echo "This means either:"
echo "1. Django container is not running"
echo "2. CI/CD pipeline failed"
echo "3. Nginx is blocking requests to Django"
echo ""

echo "🔧 Immediate Solutions:"
echo "======================"
echo ""

echo "1️⃣ Check GitHub Actions Status:"
echo "   - Go to: https://github.com/sameersheikh3999/main_dashboard/actions"
echo "   - Look for the latest 'Deploy Dashboard Backend' run"
echo "   - Check if it succeeded (green) or failed (red)"
echo ""

echo "2️⃣ If CI/CD Failed - Manual Deployment:"
echo "   SSH into your production server and run:"
echo "   -----------------------------------------"
echo "   ssh user@your-production-server"
echo "   cd /home/ubuntu/fde-dashboard"
echo "   git pull origin main"
echo "   cd backend"
echo "   docker build -t dashboard-backend-latest ."
echo "   docker stop dashboard-backend || true"
echo "   docker rm dashboard-backend || true"
echo "   docker run -d --name dashboard-backend -p 8005:8000 dashboard-backend-latest"
echo ""

echo "3️⃣ If CI/CD Succeeded - Check Container:"
echo "   SSH into your production server and run:"
echo "   -----------------------------------------"
echo "   ssh user@your-production-server"
echo "   docker ps"
echo "   docker logs dashboard-backend"
echo "   docker restart dashboard-backend"
echo ""

echo "4️⃣ Test Nginx Configuration:"
echo "   The issue might be that Nginx is not properly"
echo "   proxying requests to the Django container."
echo "   Check Nginx configuration on the server."
echo ""

echo "🎯 Quick Test Commands:"
echo "======================"
echo ""

echo "Test if Django is running on port 8005:"
echo "curl -H 'Host: api-dashboard.niete.pk' http://your-server-ip:8005/api/health/"
echo ""

echo "Test CORS directly on Django port:"
echo "curl -X OPTIONS -H 'Origin: https://dashboard.niete.pk' \\"
echo "  -H 'Access-Control-Request-Method: POST' \\"
echo "  -H 'Access-Control-Request-Headers: content-type' \\"
echo "  -I http://your-server-ip:8005/api/auth/login/"
echo ""

echo "📞 Next Steps:"
echo "=============="
echo "1. Check GitHub Actions status first"
echo "2. If failed, run manual deployment commands above"
echo "3. If succeeded, check Docker container status"
echo "4. Test the Django port directly"
echo "5. Check Nginx configuration"
echo ""

echo "🔄 After fixing, test with:"
echo "   ./check_deployment_status.sh" 